#!/bin/bash --login
#
#PBS -N loops2
#PBS -l select=1:ncpus=36
#PBS -l walltime=0:30:0
#PBS -A d167-s1770309

cd $PBS_O_WORKDIR
 
module load intel-compilers-17
module load gcc

BIN_DIR=.
DATA_FOLDER=./data
DATA_FILE=$DATA_FOLDER/results.dat

echo "cleaning..."
rm $DATA_FILE

for THREADS in 1 2 4 6 8 12 16
do
  echo "THREADS $THREADS" >> $DATA_FILE
  export OMP_NUM_THREADS=$THREADS

  echo "BIN ${BIN_DIR}/loops2" >> $DATA_FILE
  $BIN_DIR/loops2 >> $DATA_FILE
done
