#!/bin/bash --login
#
#PBS -N loops2
#PBS -A d167-s1770309
#PBS -l walltime=0:30:00
#PBS -l select=1:ncpus=36

cd $PBS_O_WORKDIR
 
module load intel-compilers-17
module load gcc

DATA_FOLDER=./data
DATA_FILE=$DATA_FOLDER/results_coursework2.txt
rm $DATA_FILE

echo "affinity" >> $DATA_FILE;
for THREADS in 1 2 4 6 8 12 16
do
  echo "THREADS ${THREADS}" >> $DATA_FILE;
  export OMP_NUM_THREADS=$THREADS;
  for i in {1..20};
  do
    ./loops2 >> $DATA_FILE;
  done
done
